/**
 * @generated by @ai-i18n/vite. Do not edit.
 * @noformat
 */

import 'vue';

declare module 'vue' {
  interface ComponentCustomProperties {
    /** Vue template 自动导入的翻译函数。 */
    readonly t: import('@ai-i18n/vite').I18nRuntime['t'];
  }
}
