import fs from 'node:fs/promises';
import path from 'node:path';
import { diagnosticMessage } from '@ai-i18n/analyzer';
import type { AiI18nFramework } from './framework.js';

const RUNTIME_AUTO_IMPORTS = [
  't',
  'setLang',
  'getLang',
  'getLangs',
  'getLangLoadState',
  'subscribe',
] as const;

export const FRAMEWORK_AUTO_IMPORTS: Record<
  AiI18nFramework,
  readonly string[]
> = {
  vanilla: RUNTIME_AUTO_IMPORTS,
  vue: [
    'useI18n',
    ...RUNTIME_AUTO_IMPORTS,
    'tRef',
    'i18nComputed',
    'tComputed',
  ],
  react: ['useI18n', ...RUNTIME_AUTO_IMPORTS],
};

const GENERATED_TYPE_MARKER = '@generated by @ai-i18n/vite. Do not edit.';

export async function writeFrameworkTypes(
  root: string,
  framework: AiI18nFramework,
  autoImport: boolean,
  dts: string | false = 'src/ai-i18n.d.ts',
): Promise<void> {
  if (dts === false) return;
  const filename = path.resolve(root, dts);
  const vueFilename = vueTemplateTypesFilename(filename);
  const vueTemplateAutoImport = framework === 'vue' && autoImport;
  const content = frameworkTypes(
    framework,
    autoImport,
    vueTemplateAutoImport
      ? `./${escapeXmlAttribute(path.basename(vueFilename))}`
      : undefined,
  );
  if (vueTemplateAutoImport) {
    // 主声明必须保持 ambient script；Vue module augmentation 放到独立模块文件，
    // 否则会覆盖 vue 原有导出，导致 ref、defineComponent 等类型消失。
    await writeOwnedGeneratedTypeFile(vueFilename, vueTemplateTypes());
  }
  await writeTypeFile(filename, content);
  if (!vueTemplateAutoImport) await removeGeneratedTypeFile(vueFilename);
}

async function writeTypeFile(filename: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(filename), { recursive: true });
  let current: string | undefined;
  try {
    current = await fs.readFile(filename, 'utf8');
  } catch {
    // 首次运行时声明文件尚不存在。
  }
  if (current !== content) await fs.writeFile(filename, content);
}

async function writeOwnedGeneratedTypeFile(
  filename: string,
  content: string,
): Promise<void> {
  let current: string;
  try {
    current = await fs.readFile(filename, 'utf8');
  } catch (error) {
    if (!isMissingFileError(error)) throw error;
    await fs.mkdir(path.dirname(filename), { recursive: true });
    try {
      await fs.writeFile(filename, content, { flag: 'wx' });
      return;
    } catch (writeError) {
      if (!hasFileSystemErrorCode(writeError, 'EEXIST')) throw writeError;
      // 创建前若出现并发写入，重新校验文件所有权，不能直接覆盖。
      return writeOwnedGeneratedTypeFile(filename, content);
    }
  }
  if (current === content) return;
  if (!current.includes(GENERATED_TYPE_MARKER)) {
    throw new Error(
      diagnosticMessage(
        `[ai-i18n] 无法生成 Vue template 类型声明 ${filename}：同名文件已存在且不属于 @ai-i18n/vite。请移动或删除该文件，或修改 dts 路径。`,
        `[ai-i18n] Cannot generate the Vue template declaration ${filename}: a file with that name already exists and is not owned by @ai-i18n/vite. Move or remove it, or configure another dts path.`,
      ),
    );
  }
  await fs.writeFile(filename, content);
}

async function removeGeneratedTypeFile(filename: string): Promise<void> {
  try {
    const content = await fs.readFile(filename, 'utf8');
    if (content.includes(GENERATED_TYPE_MARKER)) {
      await fs.rm(filename);
    }
  } catch (error) {
    if (isMissingFileError(error)) return;
    throw new Error(
      diagnosticMessage(
        `[ai-i18n] 无法清理 Vue template 类型声明 ${filename}。请检查文件权限后重试。`,
        `[ai-i18n] Failed to clean up the Vue template declaration ${filename}. Check the file permissions and try again.`,
      ),
      { cause: error },
    );
  }
}

function isMissingFileError(error: unknown): boolean {
  return hasFileSystemErrorCode(error, 'ENOENT');
}

function hasFileSystemErrorCode(error: unknown, code: string): boolean {
  return Boolean(
    error &&
    typeof error === 'object' &&
    'code' in error &&
    error.code === code,
  );
}

function vueTemplateTypesFilename(filename: string): string {
  return filename.endsWith('.d.ts')
    ? `${filename.slice(0, -'.d.ts'.length)}.vue.d.ts`
    : `${filename}.vue.d.ts`;
}

function escapeXmlAttribute(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}

function frameworkTypes(
  framework: AiI18nFramework,
  autoImport: boolean,
  vueTemplateTypesReference?: string,
): string {
  const adapterFramework = framework === 'vanilla' ? undefined : framework;
  const adapter = adapterFramework
    ? documentedDeclaration(
        'useI18n',
        `export const useI18n: import('@ai-i18n/vite/${adapterFramework}').UseI18n;`,
        '  ',
        framework,
      )
    : '';
  const vueApis =
    framework === 'vue'
      ? ([
          ['tRef', 'TranslateRef'],
          ['i18nComputed', 'I18nComputed'],
          ['tComputed', 'TranslateComputed'],
        ] as const)
      : null;
  const vueApiDeclarations = vueApis
    ? vueApis
        .map(([name, type]) =>
          documentedDeclaration(
            name,
            `export const ${name}: import('@ai-i18n/vite/vue').${type};`,
            '  ',
          ),
        )
        .join('\n\n')
    : '';
  const globals = autoImport
    ? FRAMEWORK_AUTO_IMPORTS[framework]
        .map((name) => {
          if (name === 'useI18n') {
            return documentedDeclaration(
              name,
              `declare const useI18n: import('@ai-i18n/vite/${adapterFramework}').UseI18n;`,
              '',
              framework,
            );
          }
          if (
            name === 'tRef' ||
            name === 'i18nComputed' ||
            name === 'tComputed'
          ) {
            const type =
              name === 'tRef'
                ? 'TranslateRef'
                : name === 'i18nComputed'
                  ? 'I18nComputed'
                  : 'TranslateComputed';
            return documentedDeclaration(
              name,
              `declare const ${name}: import('@ai-i18n/vite/vue').${type};`,
            );
          }
          return documentedDeclaration(
            name,
            `declare const ${name}: import('@ai-i18n/vite').I18nRuntime['${name}'];`,
          );
        })
        .join('\n\n')
    : '';
  const macro = documentedDeclaration(
    'defineI18nMessages',
    'declare const defineI18nMessages: <T>(messages: T) => T;',
  );

  const virtualModule = `declare module 'virtual:ai-i18n' {
  import type { I18nRuntime } from '@ai-i18n/vite';

${RUNTIME_API_NAMES.map((name) =>
  documentedDeclaration(
    name,
    `export const ${name}: I18nRuntime['${name}'];`,
    '  ',
  ),
).join(
  '\n\n',
)}${adapter ? `\n\n${adapter}` : ''}${vueApiDeclarations ? `\n\n${vueApiDeclarations}` : ''}
}`;

  return `${vueTemplateTypesReference ? `// eslint-disable-next-line @typescript-eslint/triple-slash-reference\n/// <reference path="${vueTemplateTypesReference}" />\n\n` : ''}/**
 * ${GENERATED_TYPE_MARKER}
 * @noformat
 */
/* eslint-disable */
// @ts-nocheck

${virtualModule}

${macro}${globals ? `\n${globals}` : ''}
`;
}

function vueTemplateTypes(): string {
  return `/**
 * ${GENERATED_TYPE_MARKER}
 * @noformat
 */

import 'vue';

declare module 'vue' {
  interface ComponentCustomProperties {
    /** Vue template 自动导入的翻译函数。 */
    readonly t: import('@ai-i18n/vite').I18nRuntime['t'];
  }
}
`;
}

const RUNTIME_API_NAMES = [
  't',
  'setLang',
  'getLang',
  'getLangs',
  'getLangLoadState',
  'subscribe',
] as const;

function documentedDeclaration(
  name: string,
  declaration: string,
  indent = '',
  framework?: AiI18nFramework,
): string {
  const lines =
    name === 'useI18n'
      ? useI18nDocumentation(framework)
      : API_DOCUMENTATION[name];
  if (!lines) return `${indent}${declaration}`;
  return [
    `${indent}/**`,
    ...lines.map((line) => `${indent} * ${line}`),
    `${indent} */`,
    `${indent}${declaration}`,
  ].join('\n');
}

function useI18nDocumentation(framework?: AiI18nFramework): readonly string[] {
  return framework === 'react'
    ? [
        'React Hook：订阅语言和翻译更新，并返回响应式翻译 API。',
        'React Hook: subscribes to language and translation updates and returns reactive translation APIs.',
        '@returns t、setLang、currentLang、langs 与语言加载状态。',
      ]
    : [
        'Vue composable：订阅语言和翻译更新，并返回响应式翻译 API。',
        'Vue composable: subscribes to language and translation updates and returns reactive translation APIs.',
        '@returns t、setLang，以及 currentLang、langs 和语言加载状态的只读 Ref。',
      ];
}

const API_DOCUMENTATION: Readonly<
  Record<string, readonly string[] | undefined>
> = {
  t: [
    '翻译可静态提取的文案；目标译文缺失时回退到源文案。',
    'Translates a statically extractable message and falls back to the source when missing.',
    '支持 t("保存")、t(messages) 和标签模板 t`你好 ${name}`。',
  ],
  setLang: [
    '切换当前语言；按需加载启用时会等待目标语言 chunk。',
    'Switches the current language and waits for its chunk when lazy loading is enabled.',
    '@returns 切换完成后的 Promise；加载失败时 reject，并保留原语言。',
  ],
  getLang: ['读取当前语言标识。', 'Returns the current language identifier.'],
  getLangs: [
    '读取配置中的语言选项，只读且保持配置顺序。',
    'Returns the configured readonly language options in configuration order.',
  ],
  getLangLoadState: [
    '读取语言加载状态：idle、loading 或 error。',
    'Returns the language loading state: idle, loading, or error.',
  ],
  subscribe: [
    '订阅语言、加载状态和翻译模块更新。',
    'Subscribes to language, loading-state, and translation-module updates.',
    '@returns 取消订阅函数。',
  ],
  tRef: [
    'Vue 专用：把文案或文案树转换为随语言更新的只读 ComputedRef。',
    'Vue only: converts a message or message tree into a readonly ComputedRef that follows language changes.',
    '请在 setup 中创建；模板中直接读取返回值，不要在模板中调用 tRef()。',
  ],
  i18nComputed: [
    'Vue Options API 专用：返回可展开到 computed 的响应式语言状态 getter。',
    'Vue Options API only: returns reactive language-state getters to spread into computed.',
    '包含 currentLang、langs、langLoadState、isLangLoading 与 langLoadError。',
  ],
  tComputed: [
    'Vue Options API 专用：返回可直接放入 computed 的响应式翻译 getter。',
    'Vue Options API only: returns a reactive translation getter for a computed option.',
    '支持字符串、标签模板和静态文案树。',
  ],
  defineI18nMessages: [
    '编译宏：标记可静态提取的文案对象或数组，无需 import。',
    'Compile-time macro: marks a statically extractable message object or array; no import is needed.',
    '构建时调用会被消除，类型上原样返回 T，不能当作运行时值引用。',
  ],
};
