const zh = {
  search: '搜索原文、译文、语境或文件…',
  filtersLabel: '筛选文案',
  localesLabel: '目标语言',
  statusLabel: '确认状态',
  suffixLabel: '文件类型',
  all: '全部',
  browseScope: '文案范围',
  currentPageScope: '当前页面',
  allPagesScope: '全部页面',
  allExtractedScope: '全部已提取',
  locateResults: '定位结果',
  backToBrowse: '返回文案列表',
  candidates: '个候选',
  locateHint: '请选择准确的文件与源码位置；同一行的重复文案可通过列号区分。',
  unreviewed: '待确认',
  reviewed: '已确认',
  tokenError: 'Token 不一致',
  showing: '显示',
  of: '/',
  messages: '条文案',
  reviewTitle: '翻译校对',
  standaloneEyebrow: 'ai-i18n / Review',
  standaloneSubtitle: '逐条确认自动译文，人工结果会直接写入项目。',
  reviewQueue: '校对队列',
  remainingShort: '待确认',
  machine: '自动译文',
  noMachine: '暂无自动译文，当前显示原文',
  useAutomatic: '填入自动译文',
  tokens: '模板 Token',
  tokenMismatch: '译文必须保留原文中的全部模板 Token。',
  final: '人工译文',
  enterTranslation: '输入译文后确认',
  scope: '作用范围',
  currentOccurrence: '当前位置',
  currentFile: '当前文件',
  allFiles: '所有文件',
  confirm: '确认译文',
  saveChanges: '保存修改',
  savedState: '已保存',
  continue: '下一条 →',
  confirmAndContinue: '确认并进入下一条',
  saveAndContinue: '保存并进入下一条',
  unsaved: '未保存',
  remove: '移除人工译文',
  occurrences: '处引用',
  openInVsCode: '在 VS Code 中打开',
  noResults: '没有符合当前筛选条件的文案。',
  noMessages: '还没有提取到文案。请先在浏览器中打开需要校对的业务页面。',
  selectMessage: '从左侧选择文案开始校对。',
  pickerNoMatch: '没有找到与该元素对应的已提取文案。',
  chooseExactOccurrence: '请先在左侧选择准确的文件位置，再保存当前位置译文。',
  saved: '人工译文已保存。',
  removed: '人工译文已移除。',
  failed: '无法读取校对数据。',
  shortcutSave: '保存',
  shortcutContinue: '保存并继续',
  shortcutMachine: '填入自动译文',
  shortcutNav: '切换文案',
  settings: '设置',
  settingsLabel: '工作台设置',
  appearance: '外观',
  themeDark: '深色',
  themeLight: '浅色',
  themeSystem: '跟随系统',
  progressLabel: '校对进度',
  remainingReview: '条待确认',
  tabSettings: '设置',
  workbenchTabsLabel: '工作台视图',
  settingsHint: '外观设置仅保存在当前浏览器，不会写入项目。',
} as const;

const en: ReviewCopy = {
  search: 'Search source, translation, context, or file…',
  filtersLabel: 'Filter messages',
  localesLabel: 'Target locales',
  statusLabel: 'Review status',
  suffixLabel: 'File type',
  all: 'All',
  browseScope: 'Message scope',
  currentPageScope: 'Current page',
  allPagesScope: 'All pages',
  allExtractedScope: 'All extracted',
  locateResults: 'Locate results',
  backToBrowse: 'Back to messages',
  candidates: 'candidates',
  locateHint:
    'Choose the exact file and source location. Columns distinguish repeated copy on the same line.',
  unreviewed: 'Needs confirmation',
  reviewed: 'Confirmed',
  tokenError: 'Token mismatch',
  showing: 'Showing',
  of: 'of',
  messages: 'messages',
  reviewTitle: 'Translation review',
  standaloneEyebrow: 'ai-i18n / Review',
  standaloneSubtitle:
    'Confirm automatic translations one by one and write reviewed copy to the project.',
  reviewQueue: 'Review queue',
  remainingShort: 'left',
  machine: 'Automatic',
  noMachine: 'No automatic translation; showing the source instead',
  useAutomatic: 'Insert automatic translation',
  tokens: 'Template tokens',
  tokenMismatch:
    'The human translation must preserve every template token from the source.',
  final: 'Human translation',
  enterTranslation: 'Enter a translation to confirm',
  scope: 'Scope',
  currentOccurrence: 'Current occurrence',
  currentFile: 'Current file',
  allFiles: 'All files',
  confirm: 'Confirm translation',
  saveChanges: 'Save changes',
  savedState: 'Saved',
  continue: 'Next →',
  confirmAndContinue: 'Confirm and continue to the next message',
  saveAndContinue: 'Save and continue to the next message',
  unsaved: 'Unsaved',
  remove: 'Remove human translation',
  occurrences: 'occurrences',
  openInVsCode: 'Open in VS Code',
  noResults: 'No messages match the current filters.',
  noMessages:
    'No messages have been extracted yet. Open the application pages you want to review first.',
  selectMessage: 'Select a message from the list to begin reviewing.',
  pickerNoMatch: 'No extracted message matches the picked element.',
  chooseExactOccurrence:
    'Select the exact file, line, and column from the locate results before saving an occurrence override.',
  saved: 'Reviewed translation saved.',
  removed: 'Reviewed translation removed.',
  failed: 'The review data could not be loaded.',
  shortcutSave: 'Save',
  shortcutContinue: 'Save & Next',
  shortcutMachine: 'Copy AI',
  shortcutNav: 'Navigate',
  settings: 'Settings',
  settingsLabel: 'Workbench settings',
  appearance: 'Appearance',
  themeDark: 'Dark',
  themeLight: 'Light',
  themeSystem: 'System',
  progressLabel: 'Review progress',
  remainingReview: 'remaining',
  tabSettings: 'Settings',
  workbenchTabsLabel: 'Workbench views',
  settingsHint:
    'Personalization is stored in this browser only and is not written to project files.',
};

export type ReviewCopy = { [Key in keyof typeof zh]: string };

export function reviewCopy(): ReviewCopy {
  const chinese = navigator.language.toLowerCase().startsWith('zh');
  return chinese ? zh : en;
}
