const zh = {
  eyebrow: 'ai-i18n · 开发环境',
  title: '翻译校对',
  description: '比较并确认最终译文。保存后，当前开发页面会立即更新。',
  search: '搜索原文、语境或文件…',
  filtersLabel: '翻译筛选',
  localesLabel: '目标语言',
  statusLabel: '确认状态',
  all: '全部',
  unreviewed: '待确认',
  reviewed: '已确认',
  tokenError: 'Token 异常',
  showing: '显示',
  of: '/ 共',
  messages: '条文案',
  source: '原文',
  context: '语境',
  machine: '自动译文',
  noMachine: '尚无自动译文，将回退原文',
  useAutomatic: '使用自动译文',
  tokens: '模板 Token',
  tokenMismatch: '人工译文必须保留原文中的全部模板 Token。',
  final: '人工译文',
  enterTranslation: '输入人工译文后即可确认',
  scope: '作用范围',
  currentFile: '当前文件',
  allFiles: '所有文件',
  confirm: '确认译文',
  saveChanges: '保存修改',
  savedState: '已保存',
  continue: '继续 →',
  confirmAndContinue: '确认并继续下一条',
  saveAndContinue: '保存并继续下一条',
  unsaved: '未保存',
  remove: '撤销人工译文',
  occurrences: '处引用',
  openInVsCode: '在 VS Code 中打开',
  noResults: '没有符合当前筛选条件的文案。',
  noMessages: '还没有提取到文案。请先在浏览器中打开需要校对的业务页面。',
  selectMessage: '从左侧选择一条文案开始校对。',
  saved: '人工译文已保存。',
  removed: '人工译文已撤销。',
  failed: '无法读取校对数据。',
  shortcutSave: '保存',
  shortcutContinue: '保存并下一步',
  shortcutMachine: '套用自动译文',
  shortcutNav: '上下切换文案',
} as const;

const en: ReviewCopy = {
  eyebrow: 'ai-i18n · local proof',
  title: 'Translation review',
  description:
    'Compare and confirm the final translation. The active development page updates after saving.',
  search: 'Search source, context, or file…',
  filtersLabel: 'Translation filters',
  localesLabel: 'Target locales',
  statusLabel: 'Confirmation status',
  all: 'All',
  unreviewed: 'Needs confirmation',
  reviewed: 'Confirmed',
  tokenError: 'Token issue',
  showing: 'Showing',
  of: 'of',
  messages: 'messages',
  source: 'Source',
  context: 'Context',
  machine: 'Automatic',
  noMachine: 'No automatic translation; source fallback is active',
  useAutomatic: 'Use automatic translation',
  tokens: 'Template tokens',
  tokenMismatch:
    'The human translation must preserve every template token from the source.',
  final: 'Human translation',
  enterTranslation: 'Enter a human translation to confirm',
  scope: 'Scope',
  currentFile: 'Current file',
  allFiles: 'All files',
  confirm: 'Confirm translation',
  saveChanges: 'Save changes',
  savedState: 'Saved',
  continue: 'Continue →',
  confirmAndContinue: 'Confirm and continue to the next message',
  saveAndContinue: 'Save and continue to the next message',
  unsaved: 'Unsaved',
  remove: 'Remove human translation',
  occurrences: 'occurrences',
  openInVsCode: 'Open in VS Code',
  noResults: 'No messages match the current filters.',
  noMessages:
    'No messages have been extracted yet. Open the application pages you want to review first.',
  selectMessage: 'Select a message from the list to begin reviewing.',
  saved: 'Reviewed translation saved.',
  removed: 'Reviewed translation removed.',
  failed: 'The review data could not be loaded.',
  shortcutSave: 'Save',
  shortcutContinue: 'Save & Next',
  shortcutMachine: 'Copy AI',
  shortcutNav: 'Navigate',
};

export type ReviewCopy = { [Key in keyof typeof zh]: string };

export function reviewCopy(): ReviewCopy {
  const chinese = navigator.language.toLowerCase().startsWith('zh');
  document.documentElement.lang = chinese ? 'zh-CN' : 'en';
  return chinese ? zh : en;
}
