import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import {
  extractFrameworkSource,
  resolveFramework,
  SOURCE_RE,
  writeFrameworkTypes,
} from '../src/framework';

const tempDirs: string[] = [];

afterEach(async () => {
  await Promise.all(
    tempDirs
      .splice(0)
      .map((directory) => fs.rm(directory, { recursive: true, force: true })),
  );
});

describe('framework integration', () => {
  it('accepts only the documented browser ESM source extensions', async () => {
    for (const extension of ['js', 'mjs', 'ts', 'mts', 'jsx', 'tsx', 'vue']) {
      expect(SOURCE_RE.test(`/workspace/src/main.${extension}`)).toBe(true);
    }
    for (const extension of ['cjs', 'cts', 'cjsx', 'ctsx', 'mjsx', 'mtsx']) {
      expect(SOURCE_RE.test(`/workspace/src/main.${extension}`)).toBe(false);
    }
    for (const extension of ['js', 'mjs', 'ts', 'mts']) {
      await expect(
        extractFrameworkSource('', `/workspace/src/main.${extension}`, 'react'),
      ).resolves.toBeUndefined();
    }
    for (const extension of ['cjs', 'cts']) {
      await expect(
        extractFrameworkSource('', `/workspace/src/main.${extension}`, 'react'),
      ).resolves.toBeNull();
    }
  });

  it('detects official Vue and React Vite plugins', () => {
    expect(resolveFramework([{ name: 'vite:vue' }])).toBe('vue');
    expect(resolveFramework([{ name: 'vite:vue-jsx' }])).toBe('vue');
    expect(resolveFramework([{ name: 'vite:react-babel' }])).toBe('react');
    expect(resolveFramework([{ name: 'vite:react-swc' }])).toBe('react');
    expect(resolveFramework([])).toBe('vanilla');
  });

  it('rejects mixed framework plugins', () => {
    expect(() =>
      resolveFramework([{ name: 'vite:vue' }, { name: 'vite:react-babel' }]),
    ).toThrow('cannot be used in the same build');
  });

  it('lets an explicit framework override detection', () => {
    expect(resolveFramework([{ name: 'vite:vue' }], 'vanilla')).toBe('vanilla');
    expect(resolveFramework([{ name: 'vite:react-babel' }], 'vue')).toBe('vue');
  });

  it('writes mode-specific virtual and global declarations', async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ai-i18n-types-'));
    tempDirs.push(root);

    await writeFrameworkTypes(root, 'vue', true);
    const source = await fs.readFile(
      path.join(root, 'src/ai-i18n.d.ts'),
      'utf8',
    );
    const vueTemplateSource = await fs.readFile(
      path.join(root, 'src/ai-i18n.vue.d.ts'),
      'utf8',
    );

    expect(source).toContain('@generated by @ai-i18n/vite');
    expect(source).toContain(
      '// eslint-disable-next-line @typescript-eslint/triple-slash-reference\n' +
        '/// <reference path="./ai-i18n.vue.d.ts" />',
    );
    expect(source).toContain('/// <reference path="./ai-i18n.vue.d.ts" />');
    expect(source).toContain('@noformat');
    expect(source).toContain('// @ts-nocheck');
    expect(source).toContain('/* eslint-disable */');
    expect(source).toContain("declare module 'virtual:ai-i18n'");
    expect(source).toContain(
      "export const getLangLoadState: I18nRuntime['getLangLoadState'];",
    );
    expect(source).toContain("import('@ai-i18n/vite/vue').UseI18n");
    expect(source).toContain(
      "export const tRef: import('@ai-i18n/vite/vue').TranslateRef;",
    );
    expect(source).toContain(
      "export const i18nComputed: import('@ai-i18n/vite/vue').I18nComputed;",
    );
    expect(source).toContain(
      "export const tComputed: import('@ai-i18n/vite/vue').TranslateComputed;",
    );
    expect(source).toContain('declare const useI18n');
    expect(source).toContain(
      "declare const tRef: import('@ai-i18n/vite/vue').TranslateRef;",
    );
    expect(source).toContain(
      "declare const i18nComputed: import('@ai-i18n/vite/vue').I18nComputed;",
    );
    expect(source).toContain(
      "declare const tComputed: import('@ai-i18n/vite/vue').TranslateComputed;",
    );
    expect(source).toContain(
      "declare const t: import('@ai-i18n/vite').I18nRuntime['t'];",
    );
    expect(source).toContain(
      "declare const getLang: import('@ai-i18n/vite').I18nRuntime['getLang'];",
    );
    expect(source).toContain(
      "declare const setLang: import('@ai-i18n/vite').I18nRuntime['setLang'];",
    );
    expect(source).toContain(
      'declare const defineI18nMessages: <T>(messages: T) => T;',
    );
    expect(source).toContain(
      '编译宏：标记可静态提取的文案对象或数组，无需 import',
    );
    expect(source).toContain('支持 t("保存")、t(messages) 和标签模板');
    expect(source).toContain('@returns 取消订阅函数');
    expect(source).toContain('随语言更新的只读 ComputedRef');
    expect(source).toContain('可展开到 computed 的响应式语言状态 getter');
    expect(source).toContain('可直接放入 computed 的响应式翻译 getter');
    expect(vueTemplateSource).toContain("import 'vue';");
    expect(vueTemplateSource).toContain("declare module 'vue'");
    expect(vueTemplateSource).not.toContain('eslint-disable');
    expect(vueTemplateSource).toContain(
      "readonly t: import('@ai-i18n/vite').I18nRuntime['t'];",
    );

    await writeFrameworkTypes(root, 'react', true);
    const react = await fs.readFile(
      path.join(root, 'src/ai-i18n.d.ts'),
      'utf8',
    );
    expect(react).toContain("import('@ai-i18n/vite/react').UseI18n");
    expect(react).toContain(
      "declare const t: import('@ai-i18n/vite').I18nRuntime['t'];",
    );
    expect(react).toContain(
      "declare const getLangLoadState: import('@ai-i18n/vite').I18nRuntime['getLangLoadState'];",
    );
    expect(react).not.toContain("import('@ai-i18n/vite/vue').UseI18n");
    expect(react).not.toContain('tRef');
    expect(react).not.toContain('i18nComputed');
    expect(react).not.toContain('tComputed');
    await expect(
      fs.access(path.join(root, 'src/ai-i18n.vue.d.ts')),
    ).rejects.toThrow();

    await writeFrameworkTypes(root, 'vanilla', true);
    const vanillaAutoImport = await fs.readFile(
      path.join(root, 'src/ai-i18n.d.ts'),
      'utf8',
    );
    expect(vanillaAutoImport).toContain(
      "declare const getLangLoadState: import('@ai-i18n/vite').I18nRuntime['getLangLoadState'];",
    );
    expect(vanillaAutoImport).not.toContain('tRef');
    expect(vanillaAutoImport).not.toContain('i18nComputed');
    expect(vanillaAutoImport).not.toContain('tComputed');

    await writeFrameworkTypes(root, 'vanilla', false);
    const vanilla = await fs.readFile(
      path.join(root, 'src/ai-i18n.d.ts'),
      'utf8',
    );
    expect(vanilla).toContain("declare module 'virtual:ai-i18n'");
    expect(vanilla).not.toContain('declare const t:');
    expect(vanilla).not.toContain('useI18n');
    expect(vanilla).toContain('declare const defineI18nMessages');
    expect(vanilla).not.toMatch(/\n\n$/);
  });

  it('derives and cleans the Vue template declaration beside a custom dts path', async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ai-i18n-types-'));
    tempDirs.push(root);
    const dts = 'types/generated/runtime-types.d.ts';
    const vueDts = path.join(root, 'types/generated/runtime-types.vue.d.ts');

    await writeFrameworkTypes(root, 'vue', true, dts);
    await expect(fs.access(vueDts)).resolves.toBeUndefined();
    expect(await fs.readFile(path.join(root, dts), 'utf8')).toContain(
      '/// <reference path="./runtime-types.vue.d.ts" />',
    );

    await writeFrameworkTypes(root, 'vue', false, dts);
    await expect(fs.access(vueDts)).rejects.toThrow();

    await fs.writeFile(vueDts, 'declare const userOwnedVueType: true;\n');
    await writeFrameworkTypes(root, 'react', true, dts);
    await expect(fs.readFile(vueDts, 'utf8')).resolves.toContain(
      'userOwnedVueType',
    );

    await writeFrameworkTypes(root, 'vue', true, false);
    await expect(
      fs.access(path.join(root, 'src/ai-i18n.d.ts')),
    ).rejects.toThrow();
  });

  it('never overwrites a user-owned Vue template declaration', async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ai-i18n-types-'));
    tempDirs.push(root);
    const dts = 'types/runtime.d.ts';
    const source = path.join(root, dts);
    const vueSource = path.join(root, 'types/runtime.vue.d.ts');
    const userContent = 'declare const userOwnedVueType: true;\n';
    await fs.mkdir(path.dirname(vueSource), { recursive: true });
    await fs.writeFile(vueSource, userContent);

    await expect(writeFrameworkTypes(root, 'vue', true, dts)).rejects.toThrow(
      'runtime.vue.d.ts',
    );
    await expect(fs.readFile(vueSource, 'utf8')).resolves.toBe(userContent);
    await expect(fs.access(source)).rejects.toThrow();

    await fs.writeFile(
      vueSource,
      '/**\n * @generated by @ai-i18n/vite. Do not edit.\n */\n',
    );
    await writeFrameworkTypes(root, 'vue', true, dts);
    await expect(fs.readFile(vueSource, 'utf8')).resolves.toContain(
      "readonly t: import('@ai-i18n/vite').I18nRuntime['t'];",
    );
  });

  it('reports generated Vue template declaration cleanup failures', async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), 'ai-i18n-types-'));
    tempDirs.push(root);
    const dts = 'types/runtime.d.ts';
    const vueSource = path.join(root, 'types/runtime.vue.d.ts');
    await writeFrameworkTypes(root, 'vue', true, dts);

    const permissionError = Object.assign(new Error('permission denied'), {
      code: 'EACCES',
    });
    const remove = vi.spyOn(fs, 'rm').mockRejectedValueOnce(permissionError);
    try {
      await expect(
        writeFrameworkTypes(root, 'react', true, dts),
      ).rejects.toThrow(vueSource);
    } finally {
      remove.mockRestore();
    }

    await expect(fs.access(vueSource)).resolves.toBeUndefined();
  });
});
