// Generated by @boses/vite. Do not edit.
declare module 'virtual:ai-i18n' {
  import type { I18nRuntime } from '@boses/vite';

  export const t: I18nRuntime['t'];
  export const setLang: I18nRuntime['setLang'];
  export const getLang: I18nRuntime['getLang'];
  export const getLangs: I18nRuntime['getLangs'];
  export const subscribe: I18nRuntime['subscribe'];
}
